services:
  web:
    build: ./web
    container_name: gaitor-demo-web
    ports:
      - "80:80"
      - "3000:3000"
  api:
    build: ./api
    container_name: gaitor-demo-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app