services:
  web:
    build: ./web
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./web/src:/app/src
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app